### ISSUE TITLE
Update the script to get zone id and record it automatically 

### ISSUE THREAD

**Issue by joshuaavalon** [joshuaavalon/SynologyCloudflareDDNS#5]
I no longer use Synology to update DDNS. So, I probably would not update it myself. Pull request is welcome.

If someone want to try, [see my script in docker](https://github.com/joshuaavalon/docker-cloudflare/blob/master/cloudflare.sh). It should be a simple port.

**Comment by MachineITSvcs** [comment]
I have written a bash script that should do the job of this script. You can find it on my github page [here](github.com/MachineITSvcs/Cloudflare-DDNS-Update)

**Comment by joshuaavalon** [comment]
@MachineITSvcs I already have a script that does it as I mentioned above. But I just do have time for changing it for Synology and test it out. If you want to update this script, you can make a pull request.

**Comment by lioujheyu** [comment]
CloudFlare has provided a large collection of examples using their API v4 in different languages. One [example](https://raw.githubusercontent.com/cloudflare/python-cloudflare/master/examples/example_update_dynamic_dns.py) in python does DDNS update with automatical zone id and record retrieval. I modified it a little bit so that it can work with synology DDNS management. You can find my code and the instruction of usage in [my repository](https://github.com/lioujheyu/synocfddns).

**Comment by dvershinin** [comment]
A better Cloudflare DDNS provider for Synology can be found [here](https://github.com/dvershinin/cloudflareddns#install-and-use-with-synology-diskstations).

* Can be configured via root domain record, e.g. `example.com` as your DDNS name
* Installable via `pip`
* Correctly handles domains with country suffixes like `.co.uk`, etc.

**Comment by joshuaavalon** [comment]
The script is updated
